### PR TITLE
Integrate redux, redux-saga, and firebase auth, Google auth

### PR DESCRIPTION
**Pull request by flozender**
Added redux, and sign-in with firebase and sign-in with Google. Uses redux-sagas to handle side-effects.

### CODE REVIEW

**Comment by PranavMahesh1** [comment]
Why delete package-lock.json?

**Comment by flozender** [comment]
> Why delete package-lock.json?

Package-lock.json is for NPM, yarn.lock is for yarn, we should only use one, so I removed npm.

**Comment by flozender** [comment]
> - Just for consistency, maybe continue 2-space indents for src/components/recordSong/RecordSong.js
> - The Google sign-in prompt shows up but after inputting credentials it doesn't actually sign me in. I'm guessing this feature will be added later

I didn't actually work on RecordSong.js, it was a an update from upstream/master branch. Error on the workflow on my side.

**Comment by PranavMahesh1** [comment]
After this pull request is merged I can fix the RecordSong.js indentation

**Comment by flozender** [comment]
Conflicts have been cleared up, let me know if we're ready to merge

**Comment by flozender** [comment]
Closes #13

**Pull request merged**
