### PR TITLE
Get available recordings

### PR DESCRIPTION
**Pull request by adamhannadev**
GET: /get-recording/(songID)/(partID)

Returns a json object: 
{
  "recordings": [
      {url},
      {url}
 ]
}

### CODE REVIEW

**Comment by flozender** [comment]
I think we're going to need the userId (UID) of the user who recorded along with the url for each recording

**Comment by adamhannadev** [comment]
> 
> 
> I think we're going to need the userId (UID) of the user who recorded along with the url for each recording

Good plan. I'll adjust it.

**Comment by adamhannadev** [comment]
Now returns: {

"recordings": [
  {
    "url": (url),
    "uid": (uid)
]
}

**Comment by flozender** [comment]
Amazing, let's merge

**Pull request merged**
